version: "3.8"

services:
  app:
    build: .
    container_name: webhook
    restart: always
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=api.fysite.id
      - LETSENCRYPT_HOST=api.fysite.id
      - LETSENCRYPT_EMAIL=testedprojected@gmail.com
    networks:
      - nginx-proxy
  redis:
    networks:
      - nginx-proxy
    image: redis:8.2-rc1-alpine
    container_name: webhook_cache
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
