name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04-lts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{ secrets.PORT || 22 }}
          script: |
            echo "Success"
